# Generated by Django 5.1.5 on 2025-04-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_food_isveg_food_category_food_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
