# Generated by Django 5.1.5 on 2025-04-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_food_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='diet_type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='Non-Vegetarian', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('All', 'All'), ('Burgers', 'Burgers'), ('Pizza', 'Pizza'), ('Salads', 'Salads'), ('Dessert', 'Dessert'), ('Drinks', 'Drinks')], default='All', max_length=100),
        ),
    ]
