# Generated by Django 5.1.5 on 2025-04-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_food_category_remove_food_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('other', 'Other'), ('burger', 'Burgers'), ('pizza', 'Pizza'), ('salad', 'Salads'), ('dessert', 'Dessert'), ('drink', 'Drinks')], default='other', max_length=100),
        ),
    ]
