# Generated by Django 5.1.5 on 2025-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_food_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='non-veg', max_length=100),
        ),
    ]
