# Generated by Django 5.1.5 on 2025-04-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='sub_category',
            field=models.CharField(choices=[('other', 'All'), ('burgers', 'Burgers'), ('pizza', 'Pizza'), ('salads', 'Salads'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='other', max_length=100),
        ),
    ]
