# Generated by Django 5.1.5 on 2025-04-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20250420_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='food',
            name='diet_type',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non-Vegetarian')], default='non-veg', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(choices=[('other', 'All'), ('burgers', 'Burgers'), ('pizza', 'Pizza'), ('salads', 'Salads'), ('dessert', 'Dessert'), ('drinks', 'Drinks')], default='other', max_length=100),
        ),
    ]
